### ISSUE TITLE
transition plan for Bill's ABNF Parser?

### ISSUE THREAD

**Issue by ajeanmahoney** [ietf-tools/tools-transition-plan#2]
The RPC uses Bill's ABNF parser for checking ABNF:
https://tools.ietf.org/tools/bap/abnf.cgi

So this tool should have a transition plan.

**Comment by rjsparks** [comment]
The maintained source for this is at https://github.com/fenner/bap

**Comment by rjsparks** [comment]
The source is now at https://github.com/ietf-tools/bap (Bill moved it here awhile back).
The plan is to add bap to author-tools. There's a temporary workaround in place for the RPC in the meantime.

**Comment by rjsparks** [comment]
This is at author-tools now.
