### ISSUE TITLE
Software releases for idnits/rfcdiff

### ISSUE THREAD

**Issue by martinthomson** [ietf-tools/tools-transition-plan#3]
I maintain tools that download and install idnits and rfcdiff automatically.  The location I used for downloading is `https://tools.ietf.org/tools/${tool}/${tool}-${version}.tgz`.  Is there a plan for hosting releases of these tools somewhere?

(Currently the above link is busted; I will have to disable installation of these tools for now.)

**Comment by rjsparks** [comment]
With Henrik's consent, I've created a pair of snapshot mirrors for idnits and rfcdiff.
See:
https://github.com/ietf-tools/idnits-mirror/
and
https://github.com/ietf-tools/rfcdiff-mirror/

I didn't capture the tarball for idnits - I can put it in the idnits-mirror repository if it would make things easier for you.

**Comment by rjsparks** [comment]
I can do so, but is a tarball what would suit you best at the moment?
I suspect you were just pulling the raw script for rfcdiff from tools before - do you also want a tarball for that?

**Comment by martinthomson** [comment]
Good point.  I only need the script(s).

**Comment by rjsparks** [comment]
Martin - there's an upcoming issue with idnits not agreeing with the 3.11.0 change to xml2rfc that will likely affect your tooling as the submission window opens.

The workaround, if it's possible for you to do so, is to 1,$s/Simplified/(Simplified|Revised)/g to accept both forms of the boilerplate until the IESG works out how long they want to accept submissions that still say Simplified.

**Comment by martinthomson** [comment]
idnits isn't on the critical path for anything, so I don't think that we need to worry about it causing issues.

Why not just make that change in the mirror?

**Comment by rjsparks** [comment]
Closing this as OBE - both are now officially in ietf-tools, and we'll track creating releases in the repos separately
